-- TABLE USERS
CREATE TABLE `heroku_a1509923c071592`.`users` ( `id` INT NOT NULL AUTO_INCREMENT , `name` VARCHAR(100) NOT NULL , `phone` VARCHAR(20) NOT NULL , `password` VARCHAR(225) NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

-- TABLE MESSAGES
CREATE TABLE `heroku_a1509923c071592`.`messages` ( `id` INT NOT NULL AUTO_INCREMENT , `message` TEXT NOT NULL , `sender` INT NOT NULL , `receiver` INT NOT NULL , `is_read` TIMESTAMP NULL DEFAULT NULL , `conversation_id` INT NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

-- TABLE CONVERSATIONS
CREATE TABLE `heroku_a1509923c071592`.`conversations` ( `id` INT NOT NULL AUTO_INCREMENT , `user_one` INT NOT NULL , `user_two` INT NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;